# Necessary Libraries

In [148]:
import pandas as pd # for pandas
import seaborn as sns # to get dataset
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder,MinMaxScaler,StandardScaler,MaxAbsScaler,RobustScaler,FunctionTransformer
from pandas.api.types import is_numeric_dtype

# Data load

In [149]:
sns.get_dataset_names() #names of the datasets

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [150]:
df = sns.load_dataset("titanic") # load the dataset
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

# Data analysis

In [151]:
df.shape

(891, 15)

In [152]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [153]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [154]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

# Data clean

In [155]:
df["age"] = df["age"].fillna(df["age"].mean()) #fillinfg the null values using mean value
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [156]:
df = df.drop(["deck","alone","alive","pclass","sibsp","class","adult_male","who",],axis =1) # droping some columns which are not needed

In [157]:
df.head()

   survived     sex   age  parch     fare embarked  embark_town
0         0    male  22.0      0   7.2500        S  Southampton
1         1  female  38.0      0  71.2833        C    Cherbourg
2         1  female  26.0      0   7.9250        S  Southampton
3         1  female  35.0      0  53.1000        S  Southampton
4         0    male  35.0      0   8.0500        S  Southampton

In [158]:
for col in df.columns:
    if not is_numeric_dtype(df[col]):
        df[col] = df[col].ffill()

df.head()

   survived     sex   age  parch     fare embarked  embark_town
0         0    male  22.0      0   7.2500        S  Southampton
1         1  female  38.0      0  71.2833        C    Cherbourg
2         1  female  26.0      0   7.9250        S  Southampton
3         1  female  35.0      0  53.1000        S  Southampton
4         0    male  35.0      0   8.0500        S  Southampton

In [159]:
df.duplicated().sum()

np.int64(119)

In [160]:
df.isna().sum() # finding the null value for each columns and sum up them

survived       0
sex            0
age            0
parch          0
fare           0
embarked       0
embark_town    0
dtype: int64

In [161]:
df1 = df.copy() # copy the dataset for further uses
df2 = df.copy()
df3 = df.copy()
df4 = df.copy()
df5 = df.copy()
df6 = df.copy()
df7 = df.copy()
df8 = df.copy()
df9 = df.copy()
df10 = df.copy()

# Data Preproscessing for Categorical data

<h2>Label encoding</h2>

In [162]:
le = LabelEncoder() # creating instance

In [163]:
lencode = le.fit(df1["sex"]) # fitting the column

In [164]:
lencode

LabelEncoder()

In [165]:
df1["sex"]=lencode.transform(df1["sex"]) #transforming it into lebel encoder
df1.head()

   survived  sex   age  parch     fare embarked  embark_town
0         0    1  22.0      0   7.2500        S  Southampton
1         1    0  38.0      0  71.2833        C    Cherbourg
2         1    0  26.0      0   7.9250        S  Southampton
3         1    0  35.0      0  53.1000        S  Southampton
4         0    1  35.0      0   8.0500        S  Southampton

In [166]:
df1.head()

   survived  sex   age  parch     fare embarked  embark_town
0         0    1  22.0      0   7.2500        S  Southampton
1         1    0  38.0      0  71.2833        C    Cherbourg
2         1    0  26.0      0   7.9250        S  Southampton
3         1    0  35.0      0  53.1000        S  Southampton
4         0    1  35.0      0   8.0500        S  Southampton

In [167]:
for col in df.columns:
    if not is_numeric_dtype(df[col]):
        df2[col] = le.fit_transform(df2[col]) # fit and transform all the categorical values into lebelencoder value?

df2.head()

   survived  sex   age  parch     fare  embarked  embark_town
0         0    1  22.0      0   7.2500         2            2
1         1    0  38.0      0  71.2833         0            0
2         1    0  26.0      0   7.9250         2            2
3         1    0  35.0      0  53.1000         2            2
4         0    1  35.0      0   8.0500         2            2

In [168]:
df2["embark_town"].value_counts()

embark_town
2    644
0    169
1     78
Name: count, dtype: int64

<h2>Ordinal encoding</h2>

In [169]:
ordi = OrdinalEncoder()

In [170]:
ordiencode = ordi.fit(df3[["embarked"]])

In [171]:
df3["embarked"] = ordiencode.transform(df3[["embarked"]])
df3.head()

   survived     sex   age  parch     fare  embarked  embark_town
0         0    male  22.0      0   7.2500       2.0  Southampton
1         1  female  38.0      0  71.2833       0.0    Cherbourg
2         1  female  26.0      0   7.9250       2.0  Southampton
3         1  female  35.0      0  53.1000       2.0  Southampton
4         0    male  35.0      0   8.0500       2.0  Southampton

In [172]:
for col in df4.columns :
    if not is_numeric_dtype(df4[col]):
        df4[col] = ordi.fit_transform(df4[[col]]) # fit and transform all the categorical values into ordinal encoder value

df4.head()

   survived  sex   age  parch     fare  embarked  embark_town
0         0  1.0  22.0      0   7.2500       2.0          2.0
1         1  0.0  38.0      0  71.2833       0.0          0.0
2         1  0.0  26.0      0   7.9250       2.0          2.0
3         1  0.0  35.0      0  53.1000       2.0          2.0
4         0  1.0  35.0      0   8.0500       2.0          2.0

<h2>One Hot Encoding</h2>

In [173]:
df5.head()

   survived     sex   age  parch     fare embarked  embark_town
0         0    male  22.0      0   7.2500        S  Southampton
1         1  female  38.0      0  71.2833        C    Cherbourg
2         1  female  26.0      0   7.9250        S  Southampton
3         1  female  35.0      0  53.1000        S  Southampton
4         0    male  35.0      0   8.0500        S  Southampton

In [174]:
df5["embark_town"].unique()

<StringArray>
['Southampton', 'Cherbourg', 'Queenstown']
Length: 3, dtype: str

In [175]:
df5["embark_town"].value_counts()

embark_town
Southampton    644
Cherbourg      169
Queenstown      78
Name: count, dtype: int64

In [176]:
ohe = OneHotEncoder(sparse_output= False)

In [177]:
onencode = ohe.fit(df5[["embark_town"]])

In [178]:
data = onencode.transform(df5[["embark_town"]]) # transform all the categorical values into one hot encoder value
data

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]], shape=(891, 3))

In [179]:
new = pd.DataFrame(data,columns=df5["embark_town"].unique())
new

     Southampton  Cherbourg  Queenstown
0            0.0        0.0         1.0
1            1.0        0.0         0.0
2            0.0        0.0         1.0
3            0.0        0.0         1.0
4            0.0        0.0         1.0
..           ...        ...         ...
886          0.0        0.0         1.0
887          0.0        0.0         1.0
888          0.0        0.0         1.0
889          1.0        0.0         0.0
890          0.0        1.0         0.0

[891 rows x 3 columns]

In [180]:
new_df = pd.concat([df5,new],axis= 1)
new_df

,survived,sex,age,parch,fare,embarked,embark_town,Southampton,Cherbourg,Queenstown
0,0,male,22.000000,0,7.2500,S,Southampton,0.0,0.0,1.0
1,1,female,38.000000,0,71.2833,C,Cherbourg,1.0,0.0,0.0
2,1,female,26.000000,0,7.9250,S,Southampton,0.0,0.0,1.0
3,1,female,35.000000,0,53.1000,S,Southampton,0.0,0.0,1.0
4,0,male,35.000000,0,8.0500,S,Southampton,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
886,0,male,27.000000,0,13.0000,S,Southampton,0.0,0.0,1.0
887,1,female,19.000000,0,30.0000,S,Southampton,0.0,0.0,1.0
888,0,female,29.699118,2,23.4500,S,Southampton,0.0,0.0,1.0
889,1,male,26.000000,0,30.0000,C,Cherbourg,1.0,0.0,0.0
890,0,male,32.000000,0,7.7500,Q,Queenstown,0.0,1.0,0.0

In [181]:
new_df1 = new_df.drop("embark_town",axis=1)
new_df1

,survived,sex,age,parch,fare,embarked,Southampton,Cherbourg,Queenstown
0,0,male,22.000000,0,7.2500,S,0.0,0.0,1.0
1,1,female,38.000000,0,71.2833,C,1.0,0.0,0.0
2,1,female,26.000000,0,7.9250,S,0.0,0.0,1.0
3,1,female,35.000000,0,53.1000,S,0.0,0.0,1.0
4,0,male,35.000000,0,8.0500,S,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
886,0,male,27.000000,0,13.0000,S,0.0,0.0,1.0
887,1,female,19.000000,0,30.0000,S,0.0,0.0,1.0
888,0,female,29.699118,2,23.4500,S,0.0,0.0,1.0
889,1,male,26.000000,0,30.0000,C,1.0,0.0,0.0
890,0,male,32.000000,0,7.7500,Q,0.0,1.0,0.0

# MinMax Scaling

In [182]:
minmax = MaxAbsScaler()

In [183]:
for col in df.columns:
    if is_numeric_dtype(df[col]):
        df6[col]=minmax.fit_transform(df6[[col]]) # fit and transform all the numerical values into min max scaler value?

df6.head()

   survived     sex     age  parch      fare embarked  embark_town
0       0.0    male  0.2750    0.0  0.014151        S  Southampton
1       1.0  female  0.4750    0.0  0.139136        C    Cherbourg
2       1.0  female  0.3250    0.0  0.015469        S  Southampton
3       1.0  female  0.4375    0.0  0.103644        S  Southampton
4       0.0    male  0.4375    0.0  0.015713        S  Southampton

# Standard Scaler

In [184]:
std = StandardScaler()

In [185]:
for col in df6.columns:
    if is_numeric_dtype(df6[col]):
        df6[col]=std.fit_transform(df6[[col]]) # fit and transform all the numarical values into standard scaler value

df6.head()

   survived     sex       age     parch      fare embarked  embark_town
0 -0.789272    male -0.592481 -0.473674 -0.502445        S  Southampton
1  1.266990  female  0.638789 -0.473674  0.786845        C    Cherbourg
2  1.266990  female -0.284663 -0.473674 -0.488854        S  Southampton
3  1.266990  female  0.407926 -0.473674  0.420730        S  Southampton
4 -0.789272    male  0.407926 -0.473674 -0.486337        S  Southampton

# Log Transform

In [186]:
import numpy as np
logtra = FunctionTransformer(np.log1p)

In [187]:
for col in df7.columns:
    if is_numeric_dtype(df7[col]):
        df7[col]=logtra.fit_transform(df7[[col]]) # fit and transform all the numarical values into log transform scaler value

df7.head()

   survived     sex       age  parch      fare embarked  embark_town
0  0.000000    male  3.135494    0.0  2.110213        S  Southampton
1  0.693147  female  3.663562    0.0  4.280593        C    Cherbourg
2  0.693147  female  3.295837    0.0  2.188856        S  Southampton
3  0.693147  female  3.583519    0.0  3.990834        S  Southampton
4  0.000000    male  3.583519    0.0  2.202765        S  Southampton

# Max Absoluate

In [188]:
max_abs = MaxAbsScaler()

In [189]:
for col in df8.columns:
    if is_numeric_dtype(df8[col]):
        df8[col]=max_abs.fit_transform(df8[[col]]) # fit and transform all the numerical values into max absoluate scaler value

df6.head()

df8.head()

   survived     sex     age  parch      fare embarked  embark_town
0       0.0    male  0.2750    0.0  0.014151        S  Southampton
1       1.0  female  0.4750    0.0  0.139136        C    Cherbourg
2       1.0  female  0.3250    0.0  0.015469        S  Southampton
3       1.0  female  0.4375    0.0  0.103644        S  Southampton
4       0.0    male  0.4375    0.0  0.015713        S  Southampton

# Robust Scaler

In [190]:
rob = RobustScaler()

In [191]:
for col in df9.columns:
    if is_numeric_dtype(df9[col]):
        df9[col]=rob.fit_transform(df9[[col]])  # fit and transform all the numerical values into robust scaler value


df9.head()

   survived     sex       age  parch      fare embarked  embark_town
0       0.0    male -0.592240    0.0 -0.312011        S  Southampton
1       1.0  female  0.638529    0.0  2.461242        C    Cherbourg
2       1.0  female -0.284548    0.0 -0.282777        S  Southampton
3       1.0  female  0.407760    0.0  1.673732        S  Southampton
4       0.0    male  0.407760    0.0 -0.277363        S  Southampton